import { useEffect, useState } from 'react'
import { initialData, initialMatches, standings, dateLabel, money, uid } from './data'
import { Badge, Empty, Field, Flag, Icon, Modal, Stat } from './components/UI'
import Management from './components/Management'
import Matches, { MatchRow } from './components/Matches'
import TicketFlow from './components/TicketFlow'
import './design/app.css'

const navigation = [['overview', 'Vista general', 'grid'], ['tournament', 'Torneo', 'trophy'], ['teams', 'Selecciones', 'people'], ['matches', 'Partidos', 'calendar'], ['venues', 'Sedes y estadios', 'pin'], ['stats', 'Estadísticas', 'chart'], ['tickets', 'Entradas', 'ticket']]
const adminNavigation = [['referees', 'Árbitros', 'shield'], ['users', 'Usuarios y roles', 'people'], ['reports', 'Reportes', 'chart'], ['access', 'Control de acceso', 'shield']]
const titles = { ...Object.fromEntries([...navigation, ...adminNavigation].map(([key, title]) => [key, title])), notifications: 'Notificaciones', profile: 'Mi cuenta' }

function App() {
  const [data, setData] = useState(initialData), [matches, setMatches] = useState(initialMatches)
  const [page, setPage] = useState(titles[location.hash.slice(1)] ? location.hash.slice(1) : 'overview')
  const [role, setRole] = useState('admin'), [profile, setProfile] = useState(initialData.users[2])
  const [tickets, setTickets] = useState([]), [notifications, setNotifications] = useState([{ id: 'welcome', owner: 'admin@demo.test', title: 'Tu torneo, en un solo lugar', text: 'La edición de demostración está lista para recorrer.', read: false }])
  const [toast, setToast] = useState(''), [selected, setSelected] = useState(null), [buying, setBuying] = useState(null)
  const [tab, setTab] = useState(''), [group, setGroup] = useState('A'), [auth, setAuth] = useState(null), [authError, setAuthError] = useState('')
  const [transfer, setTransfer] = useState(null), [ticketDetail, setTicketDetail] = useState(null), [accessResult, setAccessResult] = useState(null), [mobileOpen, setMobileOpen] = useState(false)
  const [reportFilter, setReportFilter] = useState('Todos')
  const admin = role === 'admin'
  const notify = message => setToast(message)
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 5500); return () => clearTimeout(timer) } }, [toast])
  useEffect(() => { const handler = () => { setPage(titles[location.hash.slice(1)] ? location.hash.slice(1) : 'overview'); setTab(''); setSelected(null) }; window.addEventListener('hashchange', handler); return () => window.removeEventListener('hashchange', handler) }, [])
  function navigate(next) { setPage(next); history.pushState(null, '', `#${next}`); setTab(''); setMobileOpen(false); setSelected(null); window.scrollTo(0, 0) }
  function switchRole(next) { setRole(next); setProfile(next === 'admin' ? data.users.find(u => u.id === 'u3') || initialData.users[2] : data.users.find(u => u.id === 'u1') || initialData.users[0]); navigate('overview'); setBuying(null) }
  const upcoming = matches.filter(m => m.status === 'Programado').sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time))
  const myTickets = tickets.filter(t => t.owner === profile.email)
  const myNotifications = notifications.filter(n => n.owner === profile.email)
  const unread = myNotifications.filter(n => !n.read).length
  const addNotification = (title, text, owner = profile.email) => setNotifications(prev => [{ id: uid(), title, text, owner, read: false }, ...prev])
  const teamName = id => data.teams.find(t => t.id === id)?.name || 'Selección'
  const matchName = m => `${teamName(m.home)} vs. ${teamName(m.away)}`
  function buy(match) { if (role === 'visitor') { setAuth('login'); setAuthError('Iniciá sesión para comprar entradas.'); return } setBuying(match) }
  function completePurchase(issued) { setTickets(prev => [...prev, ...issued]); setMatches(prev => prev.map(m => m.id === buying.id ? { ...m, stock: m.stock - issued.length } : m)); addNotification('Compra confirmada', `${issued.length} entradas para ${matchName(buying)}.`); navigate('tickets'); setTab('mine') }
  function login(e) {
    e.preventDefault(); const v = Object.fromEntries(new FormData(e.currentTarget)); const existing = data.users.find(u => u.email.toLowerCase() === v.email.toLowerCase())
    if (auth === 'register') {
      if (existing) return setAuthError('El correo ya está registrado.')
      if (!v.name.trim()) return setAuthError('Ingresá tu nombre y apellido.')
      if (v.password.length < 8 || v.password !== v.confirm) return setAuthError('Las contraseñas deben coincidir y tener al menos 8 caracteres.')
      const user = { id: uid(), name: v.name.trim(), email: v.email.toLowerCase(), role: 'Usuario registrado', password: v.password }
      setData(prev => ({ ...prev, users: [...prev.users, user] })); setProfile(user); setRole('user'); addNotification('Bienvenido a Solvere', 'Tu cuenta de demostración está lista.', user.email)
    } else {
      if (!existing || v.password !== (existing.password || 'demo1234')) return setAuthError('Correo o contraseña incorrectos.')
      setProfile(existing); setRole(existing.role === 'Administrador FIFA' ? 'admin' : 'user')
    }
    setAuth(null); navigate('overview'); notify('Sesión de demostración iniciada.')
  }
  const manage = kind => <Management key={kind} kind={kind} data={data} setData={setData} matches={matches} setMatches={setMatches} admin={admin} notify={notify}/>
  function groupTable(compact = false) {
    const rows = standings(data.teams, matches, group)
    return <div className="table-scroll"><table className="standings"><thead><tr><th>#</th><th>Selección</th><th>PJ</th>{!compact && <><th>G</th><th>E</th><th>P</th><th>GF</th><th>GC</th></>}<th>DG</th><th>PTS</th></tr></thead><tbody>{rows.map((t, i) => <tr key={t.id}><td><span className={i < 2 ? 'position qualified' : 'position'}>{i + 1}</span></td><td><span className="team-name"><Flag small team={t}/><strong>{t.name}</strong></span></td><td>{t.played}</td>{!compact && <><td>{t.won}</td><td>{t.drawn}</td><td>{t.lost}</td><td>{t.gf}</td><td>{t.ga}</td></>}<td>{t.gf - t.ga > 0 ? '+' : ''}{t.gf - t.ga}</td><td><strong>{t.points}</strong></td></tr>)}</tbody></table></div>
  }
  function tabs(items) { return <div className="page-tabs">{items.map(([key, name], i) => <button key={key} onClick={() => setTab(key)} className={(tab || items[0][0]) === key ? 'active' : ''}>{name}{i === 0 && <span className="tab-dot"/>}</button>)}</div> }
  function overview() {
    return <>
      <div className="page-heading"><div><div className="eyebrow">EL MUNDIAL, CONECTADO</div><h1>{admin ? 'Cada detalle cuenta.' : 'Viví el Mundial de cerca.'}</h1><p>{admin ? 'Todo lo que necesitás para organizar una experiencia inolvidable.' : 'Seguí a tu selección, consultá el fixture y encontrá tu lugar en la cancha.'}</p></div><button className="secondary" onClick={() => navigate('matches')}><Icon name="calendar"/>Ver calendario</button></div>
      <section className="hero"><div className="hero-copy"><span className="hero-label"><span/> EDICIÓN DE DEMOSTRACIÓN</span><h2>{data.tournaments[0]?.name || 'Copa Mundial 2026'}</h2><p>Un mundo. Una pasión.<br/>Toda la emoción, en un mismo lugar.</p><button onClick={() => navigate(admin ? 'tournament' : 'matches')}>{admin ? 'Gestionar torneo' : 'Explorar partidos'}<Icon name="arrow" size={18}/></button><div className="hero-meta"><span>3 países anfitriones</span><i/> <span>Fase de grupos</span></div></div><div className="pitch-art" aria-hidden="true"><div className="pitch-orbit orbit-one"/><div className="pitch-orbit orbit-two"/><div className="pitch-lines"><div className="center-line"/><div className="center-circle"/><div className="goal left"/><div className="goal right"/></div><div className="hero-number">26<span>THE WORLD IS IN PLAY</span></div></div><span className="hero-corner">SOLVERE / WORLD CUP</span></section>
      <div className="stats-grid"><Stat label="Selecciones" value={data.teams.length.toString().padStart(2, '0')} note={`${data.groups.length} grupos en competencia`} icon="people"/><Stat label="Partidos" value={matches.length.toString().padStart(2, '0')} note={`${upcoming.length} encuentros por disputar`} icon="calendar" color="blue"/><Stat label="Sedes del torneo" value={data.stadiums.length.toString().padStart(2, '0')} note="Tres escenarios, una pasión" icon="pin" color="orange"/><Stat label="Entradas emitidas" value={tickets.length.toString().padStart(2, '0')} note={`${money(tickets.reduce((s, t) => s + t.price, 0))} en ventas simuladas`} icon="ticket" color="green"/></div>
      <div className="dashboard-columns"><section className="panel upcoming-panel"><div className="panel-heading"><div><h2>Próximos partidos</h2><p>La agenda de la próxima jornada</p></div><button className="text-button" onClick={() => navigate('matches')}>Ver todos <Icon name="arrow" size={16}/></button></div>{upcoming.slice(0, 3).map(m => <MatchRow key={m.id} match={m} teams={data.teams} onClick={m => { navigate('matches'); setSelected(m) }}/>)}</section><section className="panel"><div className="panel-heading"><h2>Así van los grupos</h2><select aria-label="Grupo de posiciones" className="compact-select" value={group} onChange={e => setGroup(e.target.value)}>{data.groups.map(g => <option key={g.id} value={g.name}>Grupo {g.name}</option>)}</select></div>{groupTable(true)}<div className="panel-foot"><span className="legend-dot"/>Zona de clasificación provisional<button className="text-button" onClick={() => navigate('stats')}><Icon name="arrow" size={17}/><span className="sr-only">Ver estadísticas</span></button></div></section></div>
      <div className="bottom-grid"><section className="quick-panel"><div className="eyebrow">TODO A MANO</div><h2>Tu siguiente jugada</h2><div className="quick-links">{(admin ? [['teams', 'Gestionar selecciones', 'people', 'Planteles y cuerpos técnicos'], ['venues', 'Explorar las sedes', 'pin', 'Estadios y ciudades'], ['tickets', 'Administrar entradas', 'ticket', 'Disponibilidad por partido']] : [['teams', 'Conocé las selecciones', 'people', 'Los protagonistas del torneo'], ['tickets', 'Encontrá tu entrada', 'ticket', 'Elegí tu próximo partido'], ['stats', 'Seguí los resultados', 'chart', 'Posiciones y estadísticas']]).map(([key, title, icon, subtitle]) => <button key={key} onClick={() => navigate(key)}><span className="quick-icon"><Icon name={icon}/></span><span><strong>{title}</strong><small>{subtitle}</small></span><Icon name="chevron" size={16}/></button>)}</div></section><section className="editorial-card"><span className="eyebrow">MÁS QUE UN PARTIDO</span><h2>El mundo se encuentra<br/>en la cancha.</h2><p>Descubrí los escenarios de esta edición.</p><button className="text-button" onClick={() => navigate('venues')}>Conocer las sedes <Icon name="arrow" size={17}/></button><div className="stadium-sketch" aria-hidden="true"><div/><div/><div/></div></section></div>
    </>
  }
  function statsPage() {
    const results = matches.filter(m => m.status === 'Finalizado' && (reportFilter === 'Todos' || m.group === reportFilter))
    const goals = results.reduce((sum, m) => sum + m.score[0] + m.score[1], 0)
    const scorers = results.flatMap(m => m.events).filter(e => e.type === 'Gol').reduce((acc, e) => ({ ...acc, [e.player]: (acc[e.player] || 0) + 1 }), {})
    return <><div className="section-toolbar"><div><h2>El torneo en números</h2><p>Resultados y estadísticas de la edición de muestra.</p></div><select aria-label="Filtrar estadísticas por grupo" value={reportFilter} onChange={e => setReportFilter(e.target.value)}><option>Todos</option>{data.groups.map(g => <option key={g.id}>{g.name}</option>)}</select></div><div className="stats-grid"><Stat label="Partidos finalizados" value={results.length} note="Según el filtro seleccionado" icon="calendar"/><Stat label="Goles" value={goals} note="A partir de los resultados" icon="trophy"/><Stat label="Promedio por partido" value={results.length ? (goals / results.length).toFixed(1) : '0'} note="Goles / partidos finalizados" icon="chart"/><Stat label="Tarjetas registradas" value={results.flatMap(m => m.events).filter(e => e.type.includes('Tarjeta')).length} note="Amarillas y rojas" icon="shield"/></div><section className="panel"><div className="panel-heading"><h2>Tabla de posiciones</h2><select aria-label="Seleccionar grupo" value={group} onChange={e => setGroup(e.target.value)}>{data.groups.map(g => <option value={g.name} key={g.id}>Grupo {g.name}</option>)}</select></div>{groupTable()}<p className="panel-foot">3 puntos por victoria · 1 por empate · Orden: puntos, diferencia de gol y goles a favor.</p><div className="notice">Clasificación provisional: {standings(data.teams, matches, group).slice(0, 2).map(t => t.name).join(' y ')}. La confirmación requiere completar todos los encuentros del grupo y resolver empates.</div></section><section className="panel top-space"><div className="panel-heading"><h2>Goleadores</h2><Badge>Eventos registrados</Badge></div>{Object.entries(scorers).sort((a, b) => b[1] - a[1]).map(([name, goals], i) => <div className="list-row" key={name}><span className="position qualified">{i + 1}</span><strong>{name}</strong><span>{goals} goles</span></div>)}{!Object.keys(scorers).length && <Empty title="Sin goles registrados" text="Los eventos de los partidos aparecerán aquí."/>}</section></>
  }
  function ticketsPage() {
    return <>{tabs([['available', admin ? 'Disponibilidad' : 'Comprar entradas'], ...(role !== 'visitor' ? [['mine', 'Mis entradas']] : [])])}{tab === 'mine' && role !== 'visitor' ? <><div className="section-toolbar"><div><h2>Tus próximos recuerdos</h2><p>Consultá tus entradas y compartí la experiencia.</p></div><Badge>{myTickets.length} entradas</Badge></div><div className="ticket-grid">{myTickets.map(t => { const m = matches.find(m => m.id === t.matchId); return <article className="ticket-card" key={t.id}><div className="ticket-top"><span>SOLVERE / MATCHDAY</span><Badge tone={t.status === 'Válida' ? 'green' : 'gray'}>{t.status}</Badge></div><h3>{matchName(m)}</h3><p>{dateLabel(m.date)} · {m.time} h</p><p>{m.stadium}</p><div className="ticket-seat"><span>SECTOR<strong>{t.sector}</strong></span><span>ASIENTO<strong>{t.seat}</strong></span></div><div className="barcode" aria-hidden="true"/><small>{t.code} · Muestra sin validez</small><div className="row-actions"><button onClick={() => setTicketDetail(t)}>Ver ticket</button><button disabled={t.status !== 'Válida'} onClick={() => setTransfer(t)}>Transferir</button></div></article> })}</div>{!myTickets.length && <div className="panel"><Empty title="Tu próxima experiencia empieza acá" text="Elegí un partido y completá una compra simulada para ver tus entradas."/><div className="center-action"><button className="primary" onClick={() => setTab('available')}>Explorar partidos</button></div></div>}</> : <><div className="section-toolbar"><div><h2>Un lugar para vivirlo</h2><p>{admin ? 'Consultá el cupo y abrí cada partido para gestionar su stock.' : 'Elegí tu partido. Nosotros te guardamos la emoción.'}</p></div><Badge tone="green">Venta de demostración</Badge></div><div className="purchase-grid">{upcoming.map(m => <article className="purchase-card" key={m.id}><div className="spread"><span className="eyebrow">GRUPO {m.group}</span><Badge tone={m.stock ? 'green' : 'gray'}>{m.stock ? `${m.stock} disponibles` : 'Sin stock'}</Badge></div><div className="purchase-flags"><Flag team={data.teams.find(t => t.id === m.home)}/><span>vs</span><Flag team={data.teams.find(t => t.id === m.away)}/></div><h3>{matchName(m)}</h3><p>{dateLabel(m.date)} · {m.time} h</p><p><Icon name="pin" size={15}/>{m.stadium}</p><div className="purchase-bottom"><span>Desde <strong>{money(95)}</strong></span><button className="primary" disabled={!admin && !m.stock} onClick={() => admin ? (navigate('matches'), setSelected(m)) : buy(m)}>{admin ? 'Gestionar stock' : 'Elegir entradas'}<Icon name="arrow" size={16}/></button></div></article>)}</div></>}</>
  }
  function reportsPage() {
    const rows = matches.filter(m => reportFilter === 'Todos' || m.id === reportFilter)
    const sold = tickets.filter(t => rows.some(m => m.id === t.matchId))
    function download() { const lines = [['Partido', 'Entradas', 'Asistencias', 'Ingresos USD'], ...rows.map(m => [matchName(m), tickets.filter(t => t.matchId === m.id).length, tickets.filter(t => t.matchId === m.id && t.status === 'Utilizada').length, tickets.filter(t => t.matchId === m.id).reduce((s, t) => s + t.price, 0)])]; const csv = '\uFEFF' + lines.map(r => r.map(v => `"${String(v).replaceAll('"', '""')}"`).join(';')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = 'solvere-reporte-demo.csv'; a.click(); URL.revokeObjectURL(url); notify('Reporte CSV descargado.') }
    return <><div className="section-toolbar"><div><h2>Reportes administrativos</h2><p>Ventas y asistencia generadas durante esta sesión.</p></div><button className="primary" onClick={download}>Descargar CSV <Icon name="arrow"/></button></div><Field label="Partido"><select value={reportFilter} onChange={e => setReportFilter(e.target.value)}><option>Todos</option>{matches.map(m => <option key={m.id} value={m.id}>{matchName(m)}</option>)}</select></Field><div className="stats-grid top-space"><Stat label="Entradas emitidas" value={sold.length} icon="ticket" note="Compras simuladas"/><Stat label="Recaudación" value={money(sold.reduce((s, t) => s + t.price, 0))} icon="chart" note="Sin transacciones reales"/><Stat label="Accesos validados" value={sold.filter(t => t.status === 'Utilizada').length} icon="shield" note="Control de acceso de muestra"/></div><div className="panel table-scroll"><table><thead><tr><th>Partido</th><th>Vendidas</th><th>Asistencias</th><th>Ingresos</th></tr></thead><tbody>{rows.map(m => <tr key={m.id}><td><strong>{matchName(m)}</strong></td><td>{tickets.filter(t => t.matchId === m.id).length}</td><td>{tickets.filter(t => t.matchId === m.id && t.status === 'Utilizada').length}</td><td>{money(tickets.filter(t => t.matchId === m.id).reduce((s, t) => s + t.price, 0))}</td></tr>)}</tbody></table></div></>
  }
  function accessPage() {
    function validate(e) { e.preventDefault(); const v = Object.fromEntries(new FormData(e.currentTarget)); const ticket = tickets.find(t => t.code === v.code.trim().toUpperCase()); const m = matches.find(m => m.id === v.match); if (!ticket || ticket.matchId !== v.match || ticket.status !== 'Válida' || m.date !== v.date) { setAccessResult({ ok: false, text: 'Acceso rechazado. Verificá el código, partido, fecha o si el ticket ya fue utilizado.' }); return } setTickets(prev => prev.map(t => t.id === ticket.id ? { ...t, status: 'Utilizada' } : t)); setAccessResult({ ok: true, text: `Acceso autorizado: ${ticket.name} · ${m.stadium} · ${ticket.sector} · ${ticket.seat}. Ticket marcado como utilizado.` }) }
    return <div className="panel narrow-panel"><span className="large-icon"><Icon name="shield" size={32}/></span><h2>Control de acceso</h2><p>Simulá el ingreso con el código de una entrada emitida. Un ticket solo puede usarse una vez.</p><form onSubmit={validate}><Field label="Partido y estadio"><select name="match" required>{matches.map(m => <option value={m.id} key={m.id}>{matchName(m)} · {m.stadium}</option>)}</select></Field><Field label="Fecha del acceso simulado"><input name="date" type="date" defaultValue="2026-06-18" required/></Field><Field label="Código del ticket"><input name="code" placeholder="SOL-XXXXXXXX" required/></Field><button className="primary">Validar entrada <Icon name="check"/></button></form>{accessResult && <p role="status" className={accessResult.ok ? 'notice' : 'error'}>{accessResult.text}</p>}</div>
  }
  const protectedPage = adminNavigation.some(([key]) => key === page)
  let content
  if (protectedPage && !admin) content = <Empty title="Acceso de administrador" text="Esta sección está disponible en la vista de administrador FIFA."/>
  else if (page === 'overview') content = overview()
  else if (page === 'matches') content = <Matches data={data} matches={matches} setMatches={setMatches} admin={admin} notify={notify} onBuy={buy} selected={selected} setSelected={setSelected}/>
  else if (page === 'teams') content = <>{tabs([['teams', 'Selecciones'], ['players', 'Jugadores'], ['staff', 'Cuerpos técnicos']])}{manage(tab || 'teams')}</>
  else if (page === 'venues') content = <>{tabs([['stadiums', 'Estadios'], ['cities', 'Sedes y ciudades']])}{manage(tab || 'stadiums')}</>
  else if (page === 'tournament') content = <>{tabs([['tournaments', 'Ediciones'], ['phases', 'Fases'], ['groups', 'Grupos']])}{manage(tab || 'tournaments')}</>
  else if (page === 'stats') content = statsPage()
  else if (page === 'tickets') content = ticketsPage()
  else if (page === 'referees' || page === 'users') content = manage(page)
  else if (page === 'reports') content = reportsPage()
  else if (page === 'access') content = accessPage()
  else if (page === 'notifications') content = role === 'visitor' ? <Empty title="Iniciá sesión" text="Tus notificaciones aparecerán al ingresar."/> : <div className="panel"><div className="panel-heading"><h2>Tu actividad</h2><button className="text-button" onClick={() => setNotifications(prev => prev.map(n => n.owner === profile.email ? { ...n, read: true } : n))}>Marcar todas como leídas</button></div>{myNotifications.map(n => <div className={`notification-row ${n.read ? '' : 'unread'}`} key={n.id}><span className="stat-icon"><Icon name="bell"/></span><div><strong>{n.title}</strong><p>{n.text}</p></div>{!n.read && <Badge tone="green">Nueva</Badge>}</div>)}{!myNotifications.length && <Empty title="Todo al día" text="Las compras y transferencias aparecerán acá."/>}</div>
  else if (page === 'profile') content = role === 'visitor' ? <Empty title="Iniciá sesión" text="Ingresá para consultar tu cuenta."/> : <div className="panel narrow-panel"><h2>Tu cuenta</h2><p>Actualizá tus datos para esta sesión de demostración.</p><form onSubmit={e => { e.preventDefault(); const v = Object.fromEntries(new FormData(e.currentTarget)); if (!v.name.trim()) return notify('Ingresá un nombre válido.'); const p = { ...profile, name: v.name.trim(), ...(v.password ? { password: v.password } : {}) }; setProfile(p); setData(prev => ({ ...prev, users: prev.users.map(u => u.id === p.id ? p : u) })); notify('Datos de la cuenta actualizados.') }}><Field label="Nombre y apellido"><input name="name" defaultValue={profile.name} required/></Field><Field label="Correo electrónico"><input value={profile.email} readOnly/></Field><Field label="Nueva contraseña de prueba (opcional)"><input name="password" type="password" minLength="8" autoComplete="new-password"/></Field><button className="primary">Guardar cambios</button></form></div>
  return <div className="app-shell">
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Cerrar navegación" onClick={() => setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><button className="brand" onClick={() => navigate('overview')}><span className="brand-mark">s<span/></span><span>solvere<span className="brand-dot">.</span><small>WORLD CUP MANAGEMENT</small></span></button><div className="workspace-label">ESPACIO DEL TORNEO</div><button className="tournament-selector" onClick={() => navigate('tournament')}><span className="cup-icon"><Icon name="trophy"/></span><span><strong>Mundial 2026</strong><small>Edición de demostración</small></span><Icon name="chevron" size={15}/></button><div className="nav-label">PRINCIPAL</div><nav>{navigation.map(([key, label, icon]) => <button className={page === key ? 'active' : ''} key={key} onClick={() => { setReportFilter('Todos'); navigate(key) }}><Icon name={icon}/><span>{label}</span>{key === 'matches' && <small>{matches.length}</small>}</button>)}</nav>{admin && <><div className="nav-label">ADMINISTRACIÓN</div><nav>{adminNavigation.map(([key, label, icon]) => <button className={page === key ? 'active' : ''} key={key} onClick={() => { setReportFilter('Todos'); navigate(key) }}><Icon name={icon}/><span>{label}</span></button>)}</nav></>}<div className="sidebar-bottom"><div className="demo-note"><span className="live-dot"/>Prototipo interactivo<p>Datos de muestra. Los cambios se reinician al recargar.</p></div><button className="sidebar-user" onClick={() => role === 'visitor' ? setAuth('login') : navigate('profile')}><span className="avatar">{role === 'visitor' ? 'V' : profile.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><span><strong>{role === 'visitor' ? 'Visitante' : profile.name}</strong><small>{admin ? 'Administrador FIFA' : role === 'user' ? 'Usuario registrado' : 'Consulta pública'}</small></span><Icon name="chevron" size={15}/></button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Abrir navegación" onClick={() => setMobileOpen(true)}><Icon/></button><span>Espacio del torneo</span><Icon name="chevron" size={13}/><strong>{titles[page]}</strong></div><div className="topbar-actions"><label className="role-switch"><span>Vista demo</span><select aria-label="Cambiar perfil de demostración" value={role} onChange={e => switchRole(e.target.value)}><option value="admin">Administrador</option><option value="user">Usuario</option><option value="visitor">Visitante</option></select></label>{role !== 'visitor' ? <><button className="icon-button notification-button" aria-label={`Notificaciones, ${unread} sin leer`} onClick={() => navigate('notifications')}><Icon name="bell"/>{unread > 0 && <i/>}</button><button className="icon-button" aria-label="Cerrar sesión" onClick={() => { switchRole('visitor'); notify('Sesión cerrada.') }}><Icon name="logout"/></button></> : <button className="primary small-button" onClick={() => { setAuth('login'); setAuthError('') }}>Ingresar</button>}</div></header><main key={page}>{page !== 'overview' && <div className="page-heading interior-heading"><div><div className="eyebrow">COPA MUNDIAL / EDICIÓN 2026</div><h1>{titles[page]}</h1></div><Badge>Prototipo</Badge></div>}{content}<footer><span>© 2026 Solvere · Ingeniería de Software I</span><span>Hecho para conectar el juego.</span></footer></main></div>
    {toast && <div className="toast" role="status"><Icon name="check"/><span>{toast}</span><button aria-label="Cerrar aviso" onClick={() => setToast('')}><Icon name="close" size={16}/></button></div>}
    {buying && <TicketFlow match={matches.find(m => m.id === buying.id)} data={data} tickets={tickets} profile={profile} onClose={() => setBuying(null)} onComplete={completePurchase}/>}
    {auth && <Modal title={auth === 'register' ? 'Creá tu cuenta' : 'Bienvenido a Solvere'} onClose={() => setAuth(null)}><p className="muted">Acceso de demostración. Usá datos ficticios.</p><form key={auth} onSubmit={login}>{auth === 'register' && <Field label="Nombre y apellido"><input name="name" required/></Field>}<Field label="Correo electrónico"><input name="email" type="email" required defaultValue={auth === 'login' ? 'manuel@demo.test' : ''}/></Field><Field label="Contraseña"><input name="password" type="password" required defaultValue={auth === 'login' ? 'demo1234' : ''}/></Field>{auth === 'register' && <Field label="Confirmar contraseña"><input name="confirm" type="password" required/></Field>}{authError && <p className="error" role="alert">{authError}</p>}<button className="primary full-width">{auth === 'register' ? 'Crear cuenta' : 'Iniciar sesión'}</button></form><div className="notice small-text">Cuentas de prueba: manuel@demo.test y admin@demo.test.<br/>Contraseña: demo1234.</div><button className="text-button" onClick={() => { setAuth(auth === 'login' ? 'register' : 'login'); setAuthError('') }}>{auth === 'login' ? '¿Primera vez? Crear una cuenta' : 'Ya tengo una cuenta'}</button></Modal>}
    {transfer && <Modal title="Transferir entrada" onClose={() => setTransfer(null)}><p>Seleccioná un usuario registrado. La entrada pasará a su cuenta.</p><form onSubmit={e => { e.preventDefault(); const email = new FormData(e.currentTarget).get('email'); const user = data.users.find(u => u.email === email); const current = tickets.find(t => t.id === transfer.id); if (!user || current.status !== 'Válida' || current.owner !== profile.email) return notify('La entrada no puede transferirse.'); setTickets(prev => prev.map(t => t.id === transfer.id ? { ...t, owner: email, name: user.name } : t)); addNotification('Entrada transferida', `${transfer.code} ahora pertenece a ${user.name}.`); addNotification('Recibiste una entrada', `${profile.name} te transfirió la entrada ${transfer.code}.`, email); setTransfer(null); notify('Transferencia completada.') }}><Field label="Destinatario registrado"><select name="email" required><option value="">Seleccionar usuario…</option>{data.users.filter(u => u.email !== profile.email && u.role === 'Usuario registrado').map(u => <option value={u.email} key={u.id}>{u.name} · {u.email}</option>)}</select></Field><div className="modal-actions"><button type="button" className="secondary" onClick={() => setTransfer(null)}>Cancelar</button><button className="primary">Confirmar transferencia</button></div></form></Modal>}
    {ticketDetail && <Modal title="Tu ticket digital" onClose={() => setTicketDetail(null)}><Badge tone="green">{ticketDetail.status}</Badge><h3>{matchName(matches.find(m => m.id === ticketDetail.matchId))}</h3><dl className="details"><div><dt>Titular</dt><dd>{ticketDetail.name}</dd></div><div><dt>Sector / asiento</dt><dd>{ticketDetail.sector} / {ticketDetail.seat}</dd></div><div><dt>Código</dt><dd>{ticketDetail.code}</dd></div></dl><div className="barcode" aria-hidden="true"/><div className="notice">Ticket de muestra, sin validez para ingresar a un estadio. Podés copiar el código y probarlo desde la vista Administrador → Control de acceso.</div><button className="primary" onClick={() => setTicketDetail(null)}>Listo</button></Modal>}
  </div>
}

export default App

